name: Python App CI/CD Pipeline with Direct Deployment

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # Caching pip dependencies
    - run: |
        pip install -r requirements.txt

    # Step 3: Run tests (Optional, can be customized based on your needs)
    - name: Run tests
      run: |
        echo "Run tests"

    # Step 4: Azure Login using GitHub Secrets
    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 5: Execute Update Script on the Azure VM
    - name: Deploy to Azure VM
      run: |
        # Set the script to executable to avoid permission issues
        az vm extension set \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --vm-name ${{ secrets.VM_NAME }} \
          --name CustomScript \
          --force-update \
          --publisher Microsoft.Azure.Extensions \
          --settings '{"script": "/home/azureuser/SDA/update_app.sh"}' \
          --protected-settings '{"commandToExecute": "/bin/bash /home/azureuser/SDA/update_app.sh"}'
